title: "Indom"
description: "Indom的博客"
url: https://indom-b.tk
baseurl: ""
author: "Indom"
paginate: 5
paginate_path: "/blog/page:num/"

theme: jekyll-theme-mdui

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - jekyll-theme-mdui.gemspec
  - LICENSE.txt
  - README.md
  - vendor
  - docs
  - CHANGELOG.md
