head: 
   favicon: "https://indom-b.tk/indom.png" #  the favicon
   high_res_favicon: "https://indom-b.tk/indom.png" #  the favicon using high quality format
   apple_touch_icon: "https://indom-b.tk/indom.png" # the iOS Home button icon
   keywords: "Indom blog" #  the site keywords

uiux:
   android_chrome_color: "#3F51B5" #  the color of the Chrome address bar
   nprogress_color: "#536DFE" #  the color of the top loading progress bar
   nprogress_buffer: 200 # the top loading progress bar buffers
   meng: false # meng

background: 
   purecolor: "#FAFAFA" # the background color

img: 
   avatar: "https://indom-b.tk/indom.png" # your avatar

card: 
   card_shadow: 1 # card shadow (0-24), 0 is not displayed
   card_hoverable: true # When the hover to deepen the shadow

many_authors: false

sns_share: # SNS Share Switch
   twitter: true
   facebook: false
   googleplus: false
   weibo: true
   linkedin: false
   qq: true
   telegram: true

comment:
  used: "disqus" # disqus,livere,gitment
  # disqus config
  disqus_shortname: "" # Your disqus 
  disqus_button: true # disqus load button
  disqus_proxy: false # # disqus proxy(Do not use)
  disqus_proxy_url: "" # (Do not use)
  disqus_api_key: "" # (Do not use)
  
prism:
  themes: prism-okaidia
  components: 
    - bash 
  plugins: 

mathjax: true

baidu_site_verification: "sJmehe16f9"  # baidu site verification code

baidu_auto_push: true  # if you used baidu auto push to commit links

lang: "zh-CN"  # lang

custom_css: "" # Use the assets/css/customCss.css

custom_js: "" # Use the assets/js/customJS.js
