head: 
   favicon: "https://indom-b.tk/indom.png" #  the favicon
   high_res_favicon: "https://indom-b.tk/indom.png" #  the favicon using high quality format
   apple_touch_icon: "https://indom-b.tk/indom.png" # the iOS Home button icon
   keywords: "indom blog" #  the site keywords
header:
    m_header: true
    m_color: mdui-color-pink-400
    m_background_url: "https://i.loli.net/2018/03/24/5ab63232e1e64.jpg"
    headroom: true
    m_icon_color: pink
uiux:
   android_chrome_color: "#3F51B5" #  the color of the Chrome address bar
   nprogress_color: "#536DFE" #  the color of the top loading progress bar
   nprogress_buffer: 200 # the top loading progress bar buffers
   meng: true
background: 
   purecolor: "#f7f7f7" # the background color
img: 
   avatar: "https://indom-b.tk/indom.png" # your avatar
card: 
   card_shadow: 2 # card shadow (0-24), 0 is not displayed
   card_hoverable: true # When the hover to deepen the shadow
many_authors: false
sns_share: # SNS Share Switch
   twitter: true
   facebook: true
   googleplus: true
   weibo: true
   linkedin: true
   qq: true
   telegram: true
comment:
  used: "disqus" # disqus,livere,gitment,valine
  # disqus config
  disqus_shortname: "Indom" # Your disqus 
  disqus_button: true # disqus load button
  disqus_proxy: false # # disqus proxy(Do not use)
  disqus_proxy_url: "" # (Do not use)
  disqus_api_key: "" # (Do not use)
  # livere config
  livere_type: 'city'
  livere_data_uid: 'MTAyMC8yOTQ5Mi82MDYw'
  # gitment config
  owner: "Mysaku"
  repo: "jekyll-theme-mdui"
  client_id: "2945e26ca36ad881e9b5"
  client_secret: "816e328c91af9099932699cff0b18bc9a535213b"
  #valine config
  valine_notify: false #mail notifier
  valine_verify: false #validation code
  valine_app_id: ''
  valine_app_key: ''
  valine_placeholder: "ヾﾉ≧∀≦)o来啊，快活啊!"
passage:
  describe: true
prism:
  themes: prism-okaidia
  components: 
    - bash 
  plugins: 
mathjax: false
baidu_site_verification: ""  # baidu site verification code
baidu_auto_push: true  # if you used baidu auto push to commit links
lang: ""  # lang
deploy: "" # if you used coding pages
custom_css: "" # Use the assets/css/customCss.css
custom_js: "" # Use the assets/js/customJS.jshead: 
   favicon: "https://ooo.0o0.ooo/2017/05/27/59294212bc16e.png" #  the favicon
   high_res_favicon: "https://ooo.0o0.ooo/2017/06/08/5939484dc618e.png" #  the favicon using high quality format
   apple_touch_icon: "https://ooo.0o0.ooo/2017/06/08/5939484dc618e.png" # the iOS Home button icon
   keywords: "blog jekyll mdui theme" #  the site keywords

uiux:
   android_chrome_color: "#eeeeee" #  the color of the Chrome address bar
   nprogress_color: "#29d" #  the color of the top loading progress bar
   nprogress_buffer: 200 # the top loading progress bar buffers
   meng: false # meng

background: 
   purecolor: "#eeeeee" # the background color

img: 
   avatar: "https://ooo.0o0.ooo/2017/05/26/5928368d409dd.png" # your avatar

card: 
   card_shadow: 1 # card shadow (0-24), 0 is not displayed
   card_hoverable: false # When the hover to deepen the shadow

many_authors: false

sns_share: # SNS Share Switch
   twitter: true
   facebook: true
   googleplus: true
   weibo: true
   linkedin: true
   qq: true
   telegram: true

comment:
  used: "disqus" # disqus,livere,gitment
  # disqus config
  disqus_shortname: "" # Your disqus 
  disqus_button: true # disqus load button
  disqus_proxy: false # # disqus proxy(Do not use)
  disqus_proxy_url: "" # (Do not use)
  disqus_api_key: "" # (Do not use)
  # livere config
  livere_type: 'city'
  livere_data_uid: ''
  # gitment config
  owner: ""
  repo: ""
  client_id: ""
  client_secret: ""
  #valine config
  valine_app_id: ''
  valine_app_key: ''
  valine_placeholder: "ヾﾉ≧∀≦)o来啊，快活啊!"

prism:
  themes: prism-okaidia
  components: 
    - bash 
  plugins: 

mathjax: true


baidu_site_verification: "sJmehe16f9"  # baidu site verification code
baidu_auto_push: true  # if you used baidu auto push to commit links

lang: "zh-CN"  # lang

deploy: "" # if you used coding pages

custom_css: "" # Use the assets/css/customCss.css

custom_js: "" # Use the assets/js/customJS.js
